 name: "Adam1-CodeQL"
 on:
  workflow_dispatch:
    
 jobs:
   analyze:
     name: Analyze
     runs-on: ubuntu-latest
     steps:
     - name: Checkout repository
       uses: actions/checkout@v2
     - name: Initialize CodeQL
       uses: github/codeql-action/init@v1
       with:
         languages: bicep
     - name: Perform CodeQL Analysis
       uses: github/codeql-action/analyze@v1
       with:
         category: "bicep"
         config-file: .github/config.yml
     - name: Run Checkov
       uses: bridgecrewio/checkov-action@master
       with:
         args: --directory .
     - name: Run Template Analyzer
       run: |
         npm install -g @azure/template-analyzer
         template-analyzer analyze --path .

