 name: "Adam1-CodeQL"
 on:
  workflow_dispatch:
    
 jobs:
   analyze:
     name: Analyze
     runs-on: ubuntu-latest
     steps:
     - name: Run Template Analyzer
       run: |
         npm install -g @azure/template-analyzer
         template-analyzer analyze --path .
           - name: Perform CodeQL Analysis
